name: First workflow

on: push

jobs: 
    first_job: 
        runs-on: ubuntu-latest
        steps:
        - name: checkout Repo
          uses: actions/checkout@v4

        - name: list and read files
          run: |
            echo "First github actions job"
            ls -ltra
            cat README.md
        