name: Generate ASCII Artrwork

on: push

jobs: 
    ascii_job: 
        runs-on: ubuntu-latest
        steps:
        - name: checkout Repo
          uses: actions/checkout@v4

        - name: Executing Shell Script
          run: ./ascii-script.sh
